### ISSUE TITLE
[New Copypasta]

### ISSUE THREAD

**Issue by JesusCortina** [AntiTcb/tsmlol#3]
**What is the copypasta you'd like to add? For consistency, please have it start with exactly "TSM, aka"**
TSM, aka "Tilting Since MSI" its a NA team that fails to meet expectations ever since MSI 2015, not getting enough sacrifices to complete a ritual that would grant them international success, not even with 20+ Dyrus deaths

**Comment by arrioch** [comment]
TSM, aka "Tactical Severely Missteps", is a North American League of Legends team whose ADC always picks the worst position in a team fight.
